### PR TITLE
maximized window bug fix

### LINKED ISSUE #231: selenium // Chrome// During test running window was opened not in maximum
## Meta
Howitzer Version: 2.0.3

Driver and browser information: selenium-webdriver (3.4.2),  Chrome 59 

Gem Versions:

## Expected Behavior
with 'maximum - yes' function window should be opened in maximum
## Actual Behavior
window was opened not for maximum

### PR DESCRIPTION
**Pull request by Lec1k**
#231

### CODE REVIEW

File: generators/config/templates/capybara.rb [hunk 1]
```diff
@@ -52,6 +52,9 @@ module CapybaraHelpers
     options = Selenium::WebDriver::Firefox::Options.new(profile: ff_profile)
     params[:options] = options
   end
+  if CapybaraHelpers.chrome_browser?
```
Comment (romikoops) [inline generators/config/templates/capybara.rb]: As far as I know the problem reproduces on Headless too
