### PR TITLE
screenshot-driver-fix

### LINKED ISSUE #254: Browserstack screenshots?
## Meta
Howitzer Version:

Driver and browser information:

Gem Versions:

## Expected Behavior
A screenshot will be taken on error on browserstack.

## Actual Behavior
I get the following error:

```
capybara-screenshot could not detect a screenshot driver for 'browserstack'. Saving with default with unknown results.
WARN: Screenshot could not be saved. An exception is raised: #<NoMethodError: undefined method `render' for #<Capybara::Selenium::Driver:0x007f8c7e2ca238>>.
2017/11/22 08:57:31 [INFO] :: CLOUD VIDEO [0m 0s] - [0m 30s] URL: [NOT IMPLEMENTED]
```
## Steps to reproduce

1) Write a failing test using the browserstack driver.
2) Run rake
3) Watch it fail.

It is very possible I'm missing something, but I gripped everything looking for any combination of 'browserstack' and 'screenshot'.  Is there support yet?  If not, how can I tell it to not try to take one?

### PR DESCRIPTION
**Pull request by Lec1k**
#254

### CODE REVIEW

File: generators/config/templates/capybara.rb [hunk 1]
```diff
@@ -41,6 +41,10 @@ module CapybaraHelpers
 
 Capybara.save_path = Howitzer.log_dir
 
+Capybara::Screenshot.register_driver(Howitzer.driver.to_sym) do |driver, path|
```
Comment (romikoops) [inline generators/config/templates/capybara.rb]: it is bad approach. Please take a look at https://github.com/mattheworiordan/capybara-screenshot/blob/master/lib/capybara-screenshot.rb#L146

It means we need to add it for drivers where it is really needs and potentially in each case can be own implementation

File: generators/config/templates/drivers/browserstack.rb [hunk 2]
```diff
@@ -17,3 +17,5 @@
   url = "http://#{Howitzer.cloud_auth_login}:#{Howitzer.cloud_auth_pass}@hub.browserstack.com/wd/hub"
   CapybaraHelpers.cloud_driver(app, caps, url)
 end
+
+Capybara::Screenshot.register_driver :browserstack, &SELENIUM_BLOCK
```
Comment (romikoops) [inline generators/config/templates/drivers/browserstack.rb]:
```ruby
Capybara::Screenshot.class_eval do
  register_driver :browserstack, &registered_drivers[:selenium]
end
```
